# Generated by Django 2.2.13 on 2020-06-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
